fragment HomepageParts on Homepage {
  __typename
  hero {
    __typename
    name
    surname
    title
    subtitle
    description
    ctaPrimary
    ctaSecondary
    heroIcon
  }
  chiSono {
    __typename
    title
    description
    image
    features {
      __typename
      title
      description
      icon
    }
  }
  servizi {
    __typename
    title
    subtitle
    description
    services {
      __typename
      title
      description
      icon
      features
    }
  }
  contatti {
    __typename
    title
    description
    address
    phone
    email
    workingHours
    mapUrl
    zonesTitle
    zonesDescription
    zonesList {
      __typename
      name
    }
    appointmentTitle
    appointmentDescription
    callButtonText
    emailButtonText
  }
  footer {
    __typename
    name
    title
    description
    copyright
  }
}

fragment PostParts on Post {
  __typename
  title
  tags
  date
  excerpt
  coverImage
  body
}
